name: Security Scans

on:
  pull_request:
  push:

concurrency:
  group: security-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  security:
    name: Repository Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          scanners: "vuln,secret,misconfig"
          severity: 'HIGH,CRITICAL'
          trivyignores: '.trivyignore.yaml'
